### ISSUE TITLE
[Playground] Show warnings

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange-re.github.io#115]
Currently we don't show warnings in the playground: https://melange.re/unstable/playground/?language=Reason&code=dHlwZSBmb28gPQogIHwgT25lCiAgfCBUd287CgpsZXQgYmFyID0gdiA9PgogIHN3aXRjaCAodikgewogIHwgT25lKF8pID0%2BIDAuMAogIH07Cg%3D%3D&live=off

I think we should. cc @anmonteiro in case there are some ideas on how to this better, maybe we can make all warnings as errors at the compiler level?

**Comment by anmonteiro** [comment]
I agree we should. Why do they have to be errors? Surely there must be a way of getting the warnings from the compiler
