### ISSUE TITLE
Requirements to have a library "melange-ready"

### ISSUE THREAD

**Issue by davesnx** [melange-re/melange-re.github.io#154]
https://discuss.ocaml.org/t/whats-possible-with-melange/13806/2?u=davesnx

https://discuss.ocaml.org/t/what-are-the-limits-and-prerequisites-of-using-dependencies-with-melange/13688

**Comment by jchavarri** [comment]
Dupe of https://github.com/melange-re/melange-re.github.io/issues/132?

**Comment by davesnx** [comment]
Indeed, moving links there
