### ISSUE TITLE
Example in build system section fails

### ISSUE THREAD

**Issue by psb** [melange-re/melange-re.github.io#53]
I am trying to go through the example in the 'Build system' section of the docs, but when I do `dune build @melange` it fails with:

```
File "dune-project", line 1, characters 11-14:
1 | (lang dune 3.8)
               ^^^
Error: Version 3.8 of the dune language is not supported.
Supported versions of this extension in version 3.8 of the dune language:
- 1.0 to 1.12
- 2.0 to 2.9
- 3.0 to 3.7
```

(I'm on MacOS (ARM processor))

**Comment by jchavarri** [comment]
Thanks for the report. Dune 3.8 and the corresponding version of Melange that uses it have not been published yet, so the error makes sense.

Could you confirm that the error is gone if you try the following and then build again please?

```
opam pin add dune.dev --dev-repo
opam pin add melange.dev --dev-repo
```

If that works, we can update the instructions to replace `opam install dune melange` with the above, until the packages get published.

**Comment by psb** [comment]
`opam pin add dune.dev --dev-repo` worked but `opam pin add melange.dev --dev-repo` failed with:

```
[ERROR] The compilation of melange.dev failed at "dune build -p melange -j 7 @install".

#=== ERROR while compiling melange.dev ========================================#
# context     2.1.4 | macos/arm64 | ocaml-base-compiler.4.14.1 | pinned(git+https://github.com/melange-re/melange.git#ff0ca826)
# path        ~/Learning/Melange/_opam/.opam-switch/build/melange.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p melange -j 7 @install
# exit-code   1
# env-file    ~/.opam/log/melange-24423-e5b505.env
# output-file ~/.opam/log/melange-24423-e5b505.out
### output ###
# File "vendor/dune", line 11, characters 35-50:
# 11 |    (modules_without_implementation melange_wrapper)))
#                                         ^^^^^^^^^^^^^^^
# Error: Module Melange_wrapper doesn't exist.
```

(It did hang the first time I tried it so I had to `ctrl-c` out of it and do it again.)

**Comment by jchavarri** [comment]
Hm, I tried the command but it worked in my case. Could you try the following?

```
opam pin remove melange
opam remove melange
```

Then `opam pin add melange.dev --dev-repo` again?

**Comment by psb** [comment]
That worked. (Building did come up with an error about `refmt` and tells me to install reason. After installing reason the build worked.)

Thanks.

**Comment by jchavarri** [comment]
Thank you for the report. Fixing this in #54.
