### ISSUE TITLE
Syntax highlight

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange-re.github.io#6]
We should support `dune`, `reason` and `ocaml` at least. Maybe `opam` too.

Dune has some support for Dune and opam files: https://github.com/jchavarri/dune/tree/c28b2c6b051d20646df3ca708df3de23b63600f3/doc/exts

**Comment by jchavarri** [comment]
`reason` and `ocaml` already supported via highlightjs, which mkdocs rely on.

**Comment by feihong** [comment]
@jchavarri I think this can be closed?

**Comment by jchavarri** [comment]
we haven't found a way to highlight `dune` files yet.

**Comment by jchavarri** [comment]
Thanks!!
