### ISSUE TITLE
Document library publication and consumption

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange-re.github.io#64]
As more libraries get migrated and published in opam, this will become easier. But we should document how the transition happens.

Summary:

- the lib has no `dune` file: consume with npm, add dune config through Dune's `subdir node_modules`, use `vendored_dirs` to silence warnings
- the lib has `dune`, `dune-project` and `opam` file but is not published in opam official repo: consume with opam, use `opam pin` to point to repository
- the lib is published in opam repository: normal OCaml workflow

**Comment by psb** [comment]
Where do you want docs about this to go? Should they go under the 'package management' section (after 'opam for melange developers')?

**Comment by psb** [comment]
https://github.com/melange-re/melange-re.github.io/pull/83

**Comment by jchavarri** [comment]
Fixed in #83, thanks @psb !
