### ISSUE TITLE
Replace @bs.splice with @bs.variadic in the docs

### ISSUE THREAD

**Issue by psb** [melange-re/melange-re.github.io#65]
The docs use `@bs.splice` for variadic functions but there is no mention of it in the list of attributes and extension nodes. ReScript has deprecated `@bs.splice` in favour of `@bs.variadic` - is it the same for Melange and should `@bs.splice` be replaced with `@bs.variadic` in the docs?

**Comment by jchavarri** [comment]
I think this was a mistake. My original idea was to only use `bs.variadic` as it was introduced as a replacement for `bs.splice`. But now it is obvious that usages of `bs.splice` will still be around, so maybe we should document both. @anmonteiro what do you think?

**Comment by jchavarri** [comment]
Whatever decision we make with `bs.splice`, I think the docs examples should use `bs.variadic` and the explanation of alternative attribute should only be mentioned once.

**Comment by anmonteiro** [comment]
I think:

1. we should stick with one, and recommend it. 
2. maybe start warning in the ppx
3. as we find new usages of the old cases, convert them
4. remove the one we don't use entirely.

**Comment by psb** [comment]
As a beginner, I would like the docs to use `bs.variadic` and for that one to be recommended because then it would match ReScript. If you think [this](https://github.com/melange-re/melange-re.github.io/compare/master...psb:melange-re.github.io:splice-to-variadic) is okay, I will create a pull request.

**Comment by jchavarri** [comment]
Sounds good @psb, thanks for the initiative! :)
