### ISSUE TITLE
The `reactjs-jsx-ppx` might be renamed soon, we will have to remember to update the docs here.

### ISSUE THREAD

**Issue by psb** [melange-re/melange-re.github.io#86]
The `reactjs-jsx-ppx` might be renamed soon, we will have to remember to update the docs here.

_Originally posted by @jchavarri in https://github.com/melange-re/melange-re.github.io/pull/83#discussion_r1234335835_

**Comment by jchavarri** [comment]
ftr we can't we do this until reason-react 0.12.0 is published in opam repository.

**Comment by davesnx** [comment]
Done
